/* Generated By:JavaCC: Do not edit this line. MaintainDataConfidentialityParserConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MaintainDataConfidentialityParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CALLER = 6;
  /** RegularExpression Id. */
  int CALLEE = 7;
  /** RegularExpression Id. */
  int METHOD = 8;
  /** RegularExpression Id. */
  int COLON = 9;
  /** RegularExpression Id. */
  int COMMA = 10;
  /** RegularExpression Id. */
  int SEMICOLON = 11;
  /** RegularExpression Id. */
  int LITERAL = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\r\\n\"",
    "\"CALLER\"",
    "\"CALLEE\"",
    "\"METHOD\"",
    "\":\"",
    "\",\"",
    "\";\"",
    "<LITERAL>",
  };

}
