/* Generated By:JavaCC: Do not edit this line. PingEchoParserConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PingEchoParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LITERAL = 6;
  /** RegularExpression Id. */
  int CALLER = 7;
  /** RegularExpression Id. */
  int METHOD = 8;
  /** RegularExpression Id. */
  int CALLEE = 9;
  /** RegularExpression Id. */
  int COMMA = 10;
  /** RegularExpression Id. */
  int SEMICOLON = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\" \"",
    "\"\\t\"",
    "<LITERAL>",
    "\"CALLER:\"",
    "\"METHOD:\"",
    "\"CALLEE:\"",
    "\",\"",
    "\";\"",
  };

}
