/* Generated By:JavaCC: Do not edit this line. TacticParserConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TacticParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CALLER = 5;
  /** RegularExpression Id. */
  int CALLEE = 6;
  /** RegularExpression Id. */
  int METHOD = 7;
  /** RegularExpression Id. */
  int COMMA = 8;
  /** RegularExpression Id. */
  int SEMICOLON = 9;
  /** RegularExpression Id. */
  int IDENTIFIER = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"CALLER:\"",
    "\"CALLEE:\"",
    "\"METHOD:\"",
    "\",\"",
    "\";\"",
    "<IDENTIFIER>",
  };

}
